name: .NET

on:
   workflow_call:
  #push:
    #branches: [ develop ]
  #pull_request:
    #branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies domain
      run: dotnet restore ./TRELLOCLONE/TrelloClone/DomainLayer/Domain.csproj
    - name: Restore dependencies app
      run: dotnet restore ./TRELLOCLONE/TrelloClone/Application/Application.csproj
    - name: Restore dependencies repository
      run: dotnet restore ./TRELLOCLONE/TrelloClone/Repository/Repository.csproj
    - name: Restore dependencies main app
      run: dotnet restore ./TRELLOCLONE/TrelloClone/TrelloClone/TrelloClone.csproj
      
    - name: Build dependencies domain
      run: dotnet build ./TRELLOCLONE/TrelloClone/DomainLayer/Domain.csproj --no-restore
    - name: Build dependencies app
      run: dotnet build ./TRELLOCLONE/TrelloClone/Application/Application.csproj --no-restore
    - name: Build dependencies repository
      run: dotnet build ./TRELLOCLONE/TrelloClone/Repository/Repository.csproj --no-restore
    - name: Build dependencies main app
      run: dotnet build ./TRELLOCLONE/TrelloClone/TrelloClone/TrelloClone.csproj --no-restore
      
#    - name: Test
#      run: dotnet test ./TRELLOCLONE/TrelloClone/IntegrationTests/IntegrationTests.csproj --no-build --verbosity detailed
#./TRELLOCLONE/TrelloClone/IntegrationTests/IntegrationTests.csproj 
