name: .NET Test

on:
 push:
  branches: [ develop ]
 pull_request:
  branches: [ develop ]

jobs:
  job1:
    uses: ./.github/workflows/dotnet.yml
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
     # - run: dotnet test ./TRELLOCLONE/TrelloClone/IntegrationTests/IntegrationTests.csproj --no-build --verbosity detailed
      - name: Unit tests
        run: dotnet test ./TRELLOCLONE/TrelloClone/TrelloCloneTests/TrelloCloneTests.csproj --no-build --verbosity minimal
